### ISSUE TITLE
Need fix for drop if not found libsystemd.so

### ISSUE THREAD

**Issue by romkazor** [idlesign/systemd-logging#5]
If not found lybsystemd.so raise: ctyped.exceptions.CtypedException: Unable to find library: libsystemd.so
Simple fix:

toolbox.py
```
from ctyped.exceptions import CtypedException

try:
    from .backend_ctyped import send
except CtypedException:
    pass
```

**Comment by idlesign** [comment]
Could you elaborate on why do you need this? 
Since if you have no `systemd` (and its' library) then `systemd-logging` is basically useless.

**Comment by romkazor** [comment]
I used systemd-logging in my package, but I don't know which os system the user of my package will be using.

**Comment by idlesign** [comment]
I see. Will try to mitigate it on weekends.

**Comment by idlesign** [comment]
Implemented and available in master.
